<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?=$layout['siteTitle']?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Loading Bootstrap -->
    <link href="/static/faltui/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/static/faltui/bootstrap/css/prettify.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="/static/faltui/css/flat-ui.css" rel="stylesheet">
    <link href="/static/faltui/css/docs.css" rel="stylesheet">
    <link href="/static/default/style.css" rel="stylesheet">
    <link rel="shortcut icon" href="/static/faltui/images/favicon.ico">
    <script src="/static/faltui/js/jquery-1.8.3.min.js"></script>
    <script src="/static/faltui/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/static/faltui/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/static/faltui/js/bootstrap.min.js"></script>
    <script src="/static/faltui/js/bootstrap-select.js"></script>
    <script src="/static/faltui/js/bootstrap-switch.js"></script>
    <script src="/static/faltui/js/flatui-checkbox.js"></script>
    <script src="/static/faltui/js/flatui-radio.js"></script>
    <script src="/static/faltui/js/jquery.placeholder.js"></script>
    <script src="/static/faltui/js/typeahead.js"></script>
    <script src="/static/faltui/bootstrap/js/google-code-prettify/prettify.js"></script>
    <script src="/static/faltui/js/application.js"></script>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
    <script src="/static/faltui/js/html5shiv.js"></script>
    <script src="/static/faltui/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav style="border-radius:0;margin-bottom:0px;" class="navbar navbar-inverse navbar-embossed" role="navigation">
    <div class="max-width layoutCenter ">
        <div class="navbar-header" style="height:50px">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
                <span class="sr-only">Toggle navigation</span>
            </button>
            <a class="navbar-brand" href="#">Flat UI</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-01"  style="float:right" >
            <ul class="nav navbar-nav" >
                <li class="active"><a href="index">首页</a></li>
                <li><a href="/configuration">在线定制</a></li>
                <li><a href="#fuck">产品功能</a></li>
                <li><a href="#fuck">合作案例</a></li>
                <li><a href="#fuck">关于我们</a></li>
            </ul>
            <form class="navbar-form navbar-right" action="#" role="search">
                <div class="form-group">
                    <div class="input-group">
                        <input class="form-control" id="navbarInput-01" type="search" placeholder="Search">
	          <span class="input-group-btn">
	            <button type="submit" class="btn"><span class="fui-search"></span></button>
	          </span>
                    </div>
                </div>
            </form>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>


<?php
echo $content;
?>


</body>
</html>
