<div style="position:fixed;bottom:0;width:100%" >
  <div id="tag" class="tagsinput"></div>
  <input type="button" class="btn btn-primary btn-lg btn-block" value="购买">
</div>
<div class="row max-width layoutCenter">
        <div class="col-xs-3">
          <div class="tile">
            <img src="/static/faltui/images/icons/svg/compas.svg" alt="Compas" class="tile-image big-illustration">
            <h3 class="tile-title">Web Oriented</h3>
            <p>100% convertable to HTML/CSS layout.</p>
            <a class="btn btn-primary btn-large btn-block" href="#">Get Pro</a>
          </div>
        </div>
</div>
