<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>首页</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Loading Bootstrap -->
    <link href="/static/faltui/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/static/faltui/bootstrap/css/prettify.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="/static/faltui/css/flat-ui.css" rel="stylesheet">
    <link href="/static/faltui/css/docs.css" rel="stylesheet">
    <link href="/static/default/style.css" rel="stylesheet">
    <link rel="shortcut icon" href="/static/faltui/images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="/static/faltui/js/html5shiv.js"></script>
      <script src="/static/faltui/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

<nav style="border-radius:0;margin-bottom:0px;" class="navbar navbar-inverse navbar-embossed" role="navigation">
	<div class="max-width layoutCenter ">
		<div class="navbar-header" style="height:50px">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
			  <span class="sr-only">Toggle navigation</span>
			</button>
			<a class="navbar-brand" href="#">Flat UI</a>
		</div>
	  <div class="collapse navbar-collapse" id="navbar-collapse-01"  style="float:right" >
	    <ul class="nav navbar-nav" >           
	      <li class="active"><a href="index">首页</a></li>
	      <li><a href="/configuration">在线定制</a></li>
	      <li><a href="#fuck">产品功能</a></li>
	      <li><a href="#fuck">合作案例</a></li>
	      <li><a href="#fuck">关于我们</a></li>
	    </ul>
	    <form class="navbar-form navbar-right" action="#" role="search">
	      <div class="form-group">
	        <div class="input-group">
	          <input class="form-control" id="navbarInput-01" type="search" placeholder="Search">
	          <span class="input-group-btn">
	            <button type="submit" class="btn"><span class="fui-search"></span></button>
	          </span>            
	        </div>
	      </div>               
	    </form>
	  </div><!-- /.navbar-collapse -->
	</div>
</nav>
<div class="bs-example" style="color:#eee;background-color:#CCCCCC;height:120px;margin-bottom:20px;background-image:url('/static/default/images/banner.jpg');background-position:50% 0;" class=" max-width">
</div>
<!-- 这里显示 网站截图 -->
<div class="bs-example overHidden clearBoth  max-width layoutCenter"  >
    <div class="row clearBoth" style="margin:0;">

      <div class="thumbnail" style="border:none">

        <div class="layoutLeft col-md-4" style="width:335px;;">
          <img data-src="holder.js/300x200" alt="300x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjE1MCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjE5cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MzAweDIwMDwvdGV4dD48L3N2Zz4=" style="width: 100%; height: 200px;">
          <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p style="width:98%"><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
        <div class="layoutLeft col-md-4" style="width:335px;;">
          <img data-src="holder.js/300x200" alt="300x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjE1MCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjE5cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MzAweDIwMDwvdGV4dD48L3N2Zz4=" style="width: 100%; height: 200px;">
          <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p style="width:98%"><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
        <div class="layoutLeft col-md-4" style="width:335px;;">
          <img data-src="holder.js/300x200" alt="300x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjE1MCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjE5cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MzAweDIwMDwvdGV4dD48L3N2Zz4=" style="width: 100%; height: 200px;">
          <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p style="width:98%"><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
      </div><!-- .thumbnail end -->
    </div><!-- .row end -->
  </div><!-- .rowParent end -->
    <script src="/static/faltui/js/jquery-1.8.3.min.js"></script>
    <script src="/static/faltui/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/static/faltui/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/static/faltui/js/bootstrap.min.js"></script>
    <script src="/static/faltui/js/bootstrap-select.js"></script>
    <script src="/static/faltui/js/bootstrap-switch.js"></script>
    <script src="/static/faltui/js/flatui-checkbox.js"></script>
    <script src="/static/faltui/js/flatui-radio.js"></script>
    <script src="/static/faltui/js/jquery.tagsinput.js"></script>
    <script src="/static/faltui/js/jquery.placeholder.js"></script>
    <script src="/static/faltui/js/typeahead.js"></script>
    <script src="/static/faltui/bootstrap/js/google-code-prettify/prettify.js"></script>
    <script src="/static/faltui/js/application.js"></script>
  </body>
</html>
