<div class="bs-example" style="color:#eee;background-color:#CCCCCC;height:420px;margin-bottom:20px;background-image:url('/static/default/images/banner.jpg');background-position:50% 0;" class=" max-width">
	<div class="bs-example  max-width layoutCenter">
    <div class="bannerLeft caption ">
      <div style="background-color:rgba(31,35,38,0.5);height:300px;margin-top:50px;border-radius:3px;">
        <h6 style="text-align:center;border-bottom:1px solid rgba(155,155,155,0.5);padding:10px 0;">已经有999,999商家开通</h6>
            <div style="width:94%;margin:0 auto;">
              <p>
                我TM是一堆废话
              </p>
              <p>
                <a href="#" class="btn btn-primary btn-block" role="button"><b>免费开通</b></a> 
              </p>
            </div>
      </div>
    </div>
<div class="caption bannerRight" >
      <img src="/static/default/images/mac_wechat.png" style="padding-top:30px;" class="layoutCenter layoutBlock" alt="">
      <div style="float:right;width:60%;">
        <h3 style="margin:0;padding:0">Thumbnail label　<a style="margin-top:-8px" class="btn btn-primary" href="#">查看详细</a></h3>
        <p>我我是一句简单的介绍我是一句简单的介绍我是一句简单的介绍我是一句简单的介绍我是一句简单的介绍我是一句简单的介绍是一句简单的介绍</p>
      </div>
    </div>
	</div>
</div>
<!-- 这里显示 网站截图 -->
<div class="bs-example overHidden clearBoth  max-width layoutCenter"  >
    <div class="row clearBoth" style="margin:0;">

      <div class="thumbnail" style="border:none">

        <div class="layoutLeft col-md-4" style="width:335px;;">
          <img data-src="holder.js/300x200" alt="300x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjE1MCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjE5cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MzAweDIwMDwvdGV4dD48L3N2Zz4=" style="width: 100%; height: 200px;">
          <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p style="width:98%"><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
        <div class="layoutLeft col-md-4" style="width:335px;;">
          <img data-src="holder.js/300x200" alt="300x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjE1MCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjE5cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MzAweDIwMDwvdGV4dD48L3N2Zz4=" style="width: 100%; height: 200px;">
          <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p style="width:98%"><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
        <div class="layoutLeft col-md-4" style="width:335px;;">
          <img data-src="holder.js/300x200" alt="300x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjE1MCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjE5cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MzAweDIwMDwvdGV4dD48L3N2Zz4=" style="width: 100%; height: 200px;">
          <div class="caption">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p style="width:98%"><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>

      </div><!-- .thumbnail end -->
    </div><!-- .row end -->
  </div><!-- .rowParent end -->
